name: Apply patch from issue or manual trigger

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      patch_url:
        description: "URL to .patch or unified diff"
        required: true
      target_branch:
        description: "Base branch to patch onto"
        required: false
        default: "main"

permissions:
  contents: write
  pull-requests: write

jobs:
  apply:
    if: github.event_name == 'workflow_dispatch' || contains(github.event.issue.title, '[patch]')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Determine base branch
        id: base
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "base=${{ github.event.inputs.target_branch }}" >> $GITHUB_OUTPUT
          else
            echo "base=main" >> $GITHUB_OUTPUT
          fi

      - name: Extract patch URL
        id: extract
        run: |
          if [ "${{ github.event_name }}" = "issues" ]; then
            body="${{ github.event.issue.body }}"
            url=$(echo "$body" | grep -Eo 'https?://[^ ]+\.patch' | head -n1)
            if [ -z "$url" ]; then
              url=$(echo "$body" | grep -Eo 'https?://[^ )\n]+' | head -n1)
            fi
          else
            url="${{ github.event.inputs.patch_url }}"
          fi
          if [ -z "$url" ]; then
            echo "No patch URL found."; exit 1
          fi
          echo "url=$url" >> $GITHUB_OUTPUT
          echo "Using patch URL: $url"

      - name: Download patch
        run: |
          curl -L "${{ steps.extract.outputs.url }}" -o change.patch
          test -s change.patch

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create working branch
        run: |
          git checkout "${{ steps.base.outputs.base }}"
          BRANCH="gpt/auto-patch-${{ github.run_id }}"
          git checkout -b "$BRANCH"
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      - name: Apply patch
        run: |
          set -e
          git apply --index --whitespace=fix change.patch
          git commit -m "Apply patch from ${{ steps.extract.outputs.url }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ env.BRANCH }}
          base: ${{ steps.base.outputs.base }}
          title: "Auto PR: apply patch (${{ github.run_id }})"
          commit-message: "Apply patch from ${{ steps.extract.outputs.url }}"
          body: "This PR was generated by the apply-patch-from-issue workflow."
