name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps (if any)
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        env:
          PYTHONPATH: .
        run: |
          python -m unittest discover -s tests -p "test_*.py" || echo "No tests found; skipping."
